# Generated by Django 3.1 on 2020-08-14 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='FormarModel',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='product/')),
                ('date_of_register', models.DateField()),
                ('distirct', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantModel',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='product/')),
                ('date_of_register', models.DateField()),
                ('distirct', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Newlicence',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('gst', models.CharField(max_length=15)),
                ('firm', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('pphoto', models.ImageField(upload_to='product/')),
                ('date_of_register', models.DateField()),
                ('distirct', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('Merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.merchantmodel')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.productmodel')),
            ],
        ),
    ]
