# Generated by Django 3.1 on 2020-08-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20200814_2149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formarmodel',
            old_name='pasword',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='merchantmodel',
            old_name='distirct',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='pphoto',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='productmodel',
            name='password',
        ),
    ]
