# Generated by Django 3.1 on 2020-08-16 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200814_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlicence',
            name='photo',
            field=models.ImageField(default=False, upload_to='product/'),
        ),
    ]
