# Generated by Django 3.1 on 2020-08-18 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200817_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='photo',
            field=models.ImageField(default=False, upload_to='product/'),
        ),
    ]
