# Generated by Django 3.1 on 2020-08-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_adminmodel_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminmodel',
            old_name='fid',
            new_name='id',
        ),
    ]
