# Generated by Django 3.1 on 2020-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200818_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmodel',
            name='password',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
