# Generated by Django 3.1 on 2020-08-18 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_adminmodel_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='viewlicense',
            fields=[
                ('vid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.merchantmodel')),
                ('newlicence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.newlicence')),
            ],
        ),
    ]
