# Generated by Django 3.1 on 2020-08-19 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200819_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewlicense',
            name='admin',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app1.adminmodel'),
        ),
    ]
