# Generated by Django 3.1 on 2020-08-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_viewlicense_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlicence',
            name='status',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
