# Generated by Django 3.1 on 2020-08-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_newlicence_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectAppModel',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='product/')),
                ('date_of_register', models.DateField()),
                ('password', models.CharField(max_length=100)),
                ('gst', models.CharField(max_length=15)),
            ],
        ),
    ]
