# Generated by Django 3.1 on 2020-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rejectappmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptAppModel',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('gst', models.CharField(max_length=15)),
                ('firm', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='product/')),
                ('status', models.CharField(default=False, max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='RejectAppModel',
        ),
    ]
